#!/usr/bin/env bash

set -euo pipefail

export OS=darwin # debian
# export DOT=/usr/local/dot
export DOT=~/.dot
export SRC=/usr/local/src
export CODE=/usr/local/src
export TOOLS=/usr/local/etc

export TMUX_ENABLED=true

# sudo chown -R $USER:$USER /usr/local

if [[ $OS == "darwin" ]]; then
    # brew update && brew upgrade
    # brew install ...
    true
elif [[ $OS == "linux" ]]; then
    # apt install ...
    # sudo apt install -y kitty silversearcher-ag zsh zsh-autosuggestions zsh-syntax-highlighting build-essential lazygit gettext-base
    true
fi


if [[ $OS == "darwin" ]]; then
    export CREDENTIAL="[credential]
    helper = osxkeychain"
fi

templates=("git/gitconfig" "zsh/zshenv" "zsh/env.d/tmux.env")
for tpl in ${templates[@]}; do
    envsubst '${DOT} ${CREDENTIAL} ${TOOLS} ${CODE} ${SRC} ${TMUX_ENABLED}' < "${DOT}/${tpl}.tpl" > "${DOT}/${tpl}"
done

source_configs=("git/gitconfig" "zsh/zshenv" "zsh/zshrc" "vim/vimrc" "vim/vim" "etc/hushlogin")
for f in ${source_configs[@]}; do
    ln -hfs "${DOT}/${f}" ~/.$(basename $f)
done
