#!/usr/bin/env bash

set -euo pipefail

# valid choices are `darwin` or `crostini`
export OS=crostini
export DOT=/usr/local/dot
export SRC=/usr/local/src
export TOOLS=/usr/local/etc
export DEFAULT_EMAIL="michael@orr.co"
export TMUX_ENABLED=false

export GOPATH=$SRC/go
export PATH+=":/usr/local/go/bin"


if [[ ! -d $DOT/colors/falcon ]]; then
    git clone https://github.com/fenetikm/falcon $DOT/colors/falcon
fi

if [[ ! -d $DOT/git/gitstatus ]]; then
    git clone https://github.com/romkatv/gitstatus $DOT/git/gitstatus
fi

if [[ $OS == "darwin" ]]; then
    # brew update && brew upgrade
    # brew install vim tmux jq
    ln_args="-hfs"

    export CREDENTIAL="[credential]
    helper = osxkeychain"
elif [[ $OS == "crostini" ]]; then
    sudo apt-get update && sudo apt-get -y upgrade
    sudo apt install -y kitty silversearcher-ag zsh zsh-autosuggestions zsh-syntax-highlighting build-essential gettext-base jq
    ln_args="-fns"

    command -v go >/dev/null 2>&1 && {
        # install go if not found on path
        cd; wget "https://dl.google.com/go/$(curl https://golang.org/VERSION?m=text).linux-amd64.tar.gz"
        tar -xzf ./go1.*.tar.gz -C /usr/local/
        rm ./go1.*.tar.gz
    }

    sudo usermod -s "$(which zsh)" "${USER}"
    export CREDENTIAL="[credential]
    helper = store"
fi

templates=("git/gitconfig" "zsh/zshenv" "zsh/env.d/tmux.env")
for tpl in ${templates[@]}; do
    envsubst '${DEFAULT_EMAIL} ${DOT} ${CREDENTIAL} ${TOOLS} ${SRC} ${TMUX_ENABLED} ${XDG_CONFIG_HOME}' < "${DOT}/${tpl}.tpl" > "${DOT}/${tpl}"
done

source_configs=("git/gitconfig" "zsh/zshenv" "zsh/zshrc" "vim/vimrc" "vim/vim" "etc/hushlogin")
for f in ${source_configs[@]}; do
    ln $ln_args "${DOT}/${f}" ~/.$(basename $f)
done

vim +"PlugInstall | GoInstallBinaries" +qall
