# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", "4096", "--ioapic", "on"]
    end

    config.vm.hostname = File.basename(Dir.getwd)
    config.vm.provision :shell, :path => File.join(File.dirname(__FILE__), "scripts", "provision.sh"), :privileged => false

    config.vm.provision "puppet" do |puppet|
        puppet.manifests_path = "~/.dot/puppet/manifests"
        puppet.manifest_file = "default.pp"
        puppet.module_path = ["~/.dot/puppet/modules", "~/.puppet/modules"]
    end
end

# vim: ft=ruby
