# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", "4096"]
    end

    config.vm.hostname = File.basename(Dir.getwd)
    config.vm.provision :shell, :path => File.join(File.dirname(__FILE__), "scripts", "provision.sh"), :privileged => false
end

# vim: ft=ruby
