---
# file: roles/common/tasks/main.yml

- name: be sure ntp is installed
  apt: pkg=ntp state=installed
  tags: ntp

- name: be sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: be sure ntpd is running and enabled
  service: name=ntp state=running enabled=yes
  tags: ntp



- name: install vim
  apt: pkg=vim state=present
  sudo: yes

- name: symlink vim dotfiles
  file: >
    src=/home/{{ ansible_user_id }}/.dot/vimrc
    dest=/home/{{ ansible_user_id }}/.vimrc
    state=link
  file: >
    src=/home/{{ ansible_user_id }}/.dot/vim
    dest=/home/{{ ansible_user_id }}/.vim
    state=link
