#!/usr/bin/env bash

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_topmost               off
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on

# general space settings
yabai -m config layout                       bsp

yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

echo "yabai configuration loaded.."
