-- TODO configure me
-- https://lsp-zero.netlify.app/blog/lsp-config-overview.html

return {
--   "nvimtools/none-ls.nvim",
--   dependencies = {
--     "nvim-lua/plenary.nvim",
--     -- "gbprod/none-ls-shellcheck.nvim",
--   },
--   config = function()
--     local null_ls = require("null-ls")
--     local formatting = null_ls.builtins.formatting
--     local diagnostics = null_ls.builtins.diagnostics
--
--     -- Global format keymap
--     vim.keymap.set("n", "<leader>b", function()
--       vim.lsp.buf.format({
--         bufnr = vim.api.nvim_get_current_buf(),
--         async = true,  -- Enable async formatting
--         -- If multiple LSP servers are running, only use null-ls for formatting
--         filter = function(client)
--           return client.name == "null-ls"
--         end,
--       })
--     end, { desc = "Format buffer" })
--
--     null_ls.setup({
--       sources = {
--         -- Ruby
--         formatting.rubocop.with({
--           command = "bundle",
--           args = { "exec", "rubocop", "--auto-correct", "--stdin", "%filepath", "--stderr", "--format", "quiet" },
--         }),
--
--         -- -- Go
--         -- formatting.gofumpt,
--         -- formatting.goimports,
--
--         -- -- JavaScript/TypeScript
--         -- formatting.prettier,
--
--         -- -- Shell
--         -- formatting.shfmt,
--
--         -- -- Infrastructure
--         -- formatting.terraform_fmt,
--
--         -- -- Diagnostics/Linting
--         -- diagnostics.hadolint,
--         -- diagnostics.yamllint,
--         -- diagnostics.markdownlint,
--         -- diagnostics.sqlfluff,
--       },
--     })
--   end
}
