LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

TOOLS=/usr/local/etc
CODE=/usr/local/src
DOT=~/.dot
SRC=~/src

EDITOR=vim
VISUAL=vim

# colorize grep family commands
export GREP_OPTIONS='--color=auto'

cdpath=($SRC)

path+=$DOT/bin

for envfile in $DOT/zsh/env.d/*.env; do
    source $envfile
done

[[ -n $GOPATH ]] && path+=$GOPATH/bin
