LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

CODE=/Volumes/code
DOT=~/.dot
SRC=~/src

EDITOR=vim
VISUAL=vim

# colorize grep family commands
export GREP_OPTIONS='--color=auto'

cdpath=($SRC)

path+=$DOT/bin

for envfile in $DOT/zsh/env.d/*.env; do
    source $envfile
done
