source $ZPLUG_HOME/init.zsh

for file in $DOT/zsh/conf/*.zsh; do
    source $file
done

# compinit happens here
zplug load

source "$DOT/zsh/keybindings/keybindings.zsh"
source "$DOT/zsh/theme/michaelorr-theme.zsh"
